# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rockPaperScissors' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rockPaperScissors
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  target 'rockPaperScissors-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rockPaperScissorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rockPaperScissors-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
