//AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const CLEAN_NEW_ACCOUNT_FLAG = 'CLEAN_NEW_ACCOUNT_FLAG';

//SIGN IN
export const UPDATE_SIGNIN_EMAIL_FIELD = 'UPDATE_SIGNIN_EMAIL_FIELD';
export const UPDATE_SIGNIN_PASSWORD_FIELD = 'UPDATE_SIGNIN_PASSWORD_FIELD';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGNING_UP = 'SIGNING_UP';

//SIGN UP SCREEN
export const UPDATE_SIGNUP_USERNAME_FIELD = 'UPDATE_SIGNUP_USERNAME_FIELD';
export const UPDATE_SIGNUP_EMAIL_FIELD = 'UPDATE_SIGNUP_EMAIL_FIELD';
export const UPDATE_SIGNUP_PASSWORD_FIELD = 'UPDATE_SIGNUP_PASSWORD_FIELD';

//PLAY
export const PLAY = 'PLAY';
export const PLAY_AGAIN = 'PLAY_AGAIN';
export const SET_PLAYER_TROPHIES = 'SET_PLAYER_TROPHIES';

//LEADERBOARD
export const UPDATE_LEADERBOARD_LIST = 'UPDATE_LEADERBOARD_LIST';
